title: Dog Hotel
description: >- # this means to ignore newlines until "baseurl:"
  Cuidador de animais em Apucarana
baseurl: "/hospedagemparacaesapucarana" # the subpath of your site, e.g. /blog
url: "https://conttudoweb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: #fff

# Build settings
markdown: kramdown
parmalink: /:title/
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
